language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
- (rustup component add rustfmt || echo "rustfmt already installed")
script:
- cargo fmt -- --check
- cargo build --verbose
- cargo test --verbose
